name: CI

on:
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout do código
      uses: actions/checkout@v2
    
    - name: Verificar branch de origem
      run: |
        if [ "${{ github.event.pull_request.head.ref }}" != "release" ]  && [ "${{ github.event.pull_request.base.ref }}" = "main" ]; then
          echo "As pull requests da branch 'release' para 'main' não são permitidas."
          exit 1
        fi