name: Deploy release for AWS and Commit to Main

on:
  workflow_dispatch:
  push:
    branches:
      - release

env:
  _ENVIRONMENT: development
  _REPOSITORY_NAME: github-action-nodejs-serverless

jobs:
  DeployServerless:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: npm install
      - name: Serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          LOG_LEVEL: debug
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

  DeployToMain:
    name: Deploy to main
    runs-on: ubuntu-latest
    needs: DeployServerless
    if: github.ref == 'refs/heads/release' && github.event_name == 'push'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{secrets.TOKEN_GIT}}
      - name: Set up Git
        uses: actions/setup-git@v2
      - name: Merge release into main
        run: |
          git merge --no-ff ${{ github.event.before }}
          git push origin main
