name: Deploy release for AWS and Commit to Main

on:
  workflow_dispatch:
  push:
    branches:
      - develop

env:
  _ENVIRONMENT: development
  _REPOSITORY_NAME: github-action-nodejs-serverless

jobs:
  ValidatePullRequest:
    name: validate
    runs-on: ubuntu-latest
    steps:
      # Adicione os passos necessários para validar o pull request
      - name: Validate pull request
        run: echo "Validating pull request"
      # Defina uma saída de aprovação, por exemplo, usando uma saída de script
      - name: Set approval status
        id: approval
        run: echo "::set-output name=approved::true"
        
  DeployServerless:
    name: deploy
    runs-on: ubuntu-latest
    needs: ValidatePullRequest
    if: ${{ needs.ValidatePullRequest.outputs.approved == 'true' }}
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm install
        run: npm install
      - name: Serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          LOG_LEVEL: debug
          AWS_REGION_KEY: ${{ secrets.AWS_REGION_KEY }}
          COGNITO_CLIENT_ID_KEY: ${{ secrets.COGNITO_CLIENT_ID_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}