name: Merge develop into release

on:
  push:
    branches:
      - develop

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Criar Pull Request para Release
        uses: MarceloJau/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          title: "[Automated] Merge da develop para release"
          body: "Este pull request foi gerado automaticamente para mesclar as alterações da branch develop na branch release."

  await_approval:
    runs-on: ubuntu-latest
    needs: create_pull_request
    steps:
      - name: Aprovar Pull Request
        uses: MarceloJau/action-tmate@v3
